// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyValueResponse.proto

package ca.NetSysLab.ProtocolBuffers;

public final class KeyValueResponse {
  private KeyValueResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KVResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KVResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 errCode = 1;</code>
     * @return The errCode.
     */
    int getErrCode();

    /**
     * <code>optional bytes value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 2;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>optional int32 pid = 3;</code>
     * @return Whether the pid field is set.
     */
    boolean hasPid();
    /**
     * <code>optional int32 pid = 3;</code>
     * @return The pid.
     */
    int getPid();

    /**
     * <code>optional int32 version = 4;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 4;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return Whether the overloadWaitTime field is set.
     */
    boolean hasOverloadWaitTime();
    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return The overloadWaitTime.
     */
    int getOverloadWaitTime();

    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return Whether the membershipCount field is set.
     */
    boolean hasMembershipCount();
    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return The membershipCount.
     */
    int getMembershipCount();

    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo> 
        getMembershipInfoList();
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo getMembershipInfo(int index);
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    int getMembershipInfoCount();
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    java.util.List<? extends ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder> 
        getMembershipInfoOrBuilderList();
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder getMembershipInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code KVResponse}
   */
  public static final class KVResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KVResponse)
      KVResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KVResponse.newBuilder() to construct.
    private KVResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KVResponse() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      membershipInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KVResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.class, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.Builder.class);
    }

    public interface MembershipInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:KVResponse.MembershipInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string addressPair = 1;</code>
       * @return The addressPair.
       */
      java.lang.String getAddressPair();
      /**
       * <code>string addressPair = 1;</code>
       * @return The bytes for addressPair.
       */
      com.google.protobuf.ByteString
          getAddressPairBytes();

      /**
       * <code>int64 time = 2;</code>
       * @return The time.
       */
      long getTime();
    }
    /**
     * Protobuf type {@code KVResponse.MembershipInfo}
     */
    public static final class MembershipInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:KVResponse.MembershipInfo)
        MembershipInfoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use MembershipInfo.newBuilder() to construct.
      private MembershipInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private MembershipInfo() {
        addressPair_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new MembershipInfo();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_MembershipInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_MembershipInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.class, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder.class);
      }

      public static final int ADDRESSPAIR_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object addressPair_ = "";
      /**
       * <code>string addressPair = 1;</code>
       * @return The addressPair.
       */
      @java.lang.Override
      public java.lang.String getAddressPair() {
        java.lang.Object ref = addressPair_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressPair_ = s;
          return s;
        }
      }
      /**
       * <code>string addressPair = 1;</code>
       * @return The bytes for addressPair.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAddressPairBytes() {
        java.lang.Object ref = addressPair_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressPair_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TIME_FIELD_NUMBER = 2;
      private long time_ = 0L;
      /**
       * <code>int64 time = 2;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return time_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addressPair_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressPair_);
        }
        if (time_ != 0L) {
          output.writeInt64(2, time_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addressPair_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressPair_);
        }
        if (time_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, time_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo)) {
          return super.equals(obj);
        }
        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo other = (ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo) obj;

        if (!getAddressPair()
            .equals(other.getAddressPair())) return false;
        if (getTime()
            != other.getTime()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ADDRESSPAIR_FIELD_NUMBER;
        hash = (53 * hash) + getAddressPair().hashCode();
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code KVResponse.MembershipInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:KVResponse.MembershipInfo)
          ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_MembershipInfo_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_MembershipInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.class, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder.class);
        }

        // Construct using ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          addressPair_ = "";
          time_ = 0L;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_MembershipInfo_descriptor;
        }

        @java.lang.Override
        public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo getDefaultInstanceForType() {
          return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.getDefaultInstance();
        }

        @java.lang.Override
        public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo build() {
          ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo buildPartial() {
          ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo result = new ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.addressPair_ = addressPair_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.time_ = time_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo) {
            return mergeFrom((ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo other) {
          if (other == ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.getDefaultInstance()) return this;
          if (!other.getAddressPair().isEmpty()) {
            addressPair_ = other.addressPair_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.getTime() != 0L) {
            setTime(other.getTime());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  addressPair_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 16: {
                  time_ = input.readInt64();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object addressPair_ = "";
        /**
         * <code>string addressPair = 1;</code>
         * @return The addressPair.
         */
        public java.lang.String getAddressPair() {
          java.lang.Object ref = addressPair_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            addressPair_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string addressPair = 1;</code>
         * @return The bytes for addressPair.
         */
        public com.google.protobuf.ByteString
            getAddressPairBytes() {
          java.lang.Object ref = addressPair_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            addressPair_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string addressPair = 1;</code>
         * @param value The addressPair to set.
         * @return This builder for chaining.
         */
        public Builder setAddressPair(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          addressPair_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string addressPair = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearAddressPair() {
          addressPair_ = getDefaultInstance().getAddressPair();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string addressPair = 1;</code>
         * @param value The bytes for addressPair to set.
         * @return This builder for chaining.
         */
        public Builder setAddressPairBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          addressPair_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private long time_ ;
        /**
         * <code>int64 time = 2;</code>
         * @return The time.
         */
        @java.lang.Override
        public long getTime() {
          return time_;
        }
        /**
         * <code>int64 time = 2;</code>
         * @param value The time to set.
         * @return This builder for chaining.
         */
        public Builder setTime(long value) {
          
          time_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>int64 time = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearTime() {
          bitField0_ = (bitField0_ & ~0x00000002);
          time_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:KVResponse.MembershipInfo)
      }

      // @@protoc_insertion_point(class_scope:KVResponse.MembershipInfo)
      private static final ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo();
      }

      public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<MembershipInfo>
          PARSER = new com.google.protobuf.AbstractParser<MembershipInfo>() {
        @java.lang.Override
        public MembershipInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<MembershipInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<MembershipInfo> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_ = 0;
    /**
     * <code>uint32 errCode = 1;</code>
     * @return The errCode.
     */
    @java.lang.Override
    public int getErrCode() {
      return errCode_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int PID_FIELD_NUMBER = 3;
    private int pid_ = 0;
    /**
     * <code>optional int32 pid = 3;</code>
     * @return Whether the pid field is set.
     */
    @java.lang.Override
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 pid = 3;</code>
     * @return The pid.
     */
    @java.lang.Override
    public int getPid() {
      return pid_;
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_ = 0;
    /**
     * <code>optional int32 version = 4;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 version = 4;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int OVERLOADWAITTIME_FIELD_NUMBER = 5;
    private int overloadWaitTime_ = 0;
    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return Whether the overloadWaitTime field is set.
     */
    @java.lang.Override
    public boolean hasOverloadWaitTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return The overloadWaitTime.
     */
    @java.lang.Override
    public int getOverloadWaitTime() {
      return overloadWaitTime_;
    }

    public static final int MEMBERSHIPCOUNT_FIELD_NUMBER = 6;
    private int membershipCount_ = 0;
    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return Whether the membershipCount field is set.
     */
    @java.lang.Override
    public boolean hasMembershipCount() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return The membershipCount.
     */
    @java.lang.Override
    public int getMembershipCount() {
      return membershipCount_;
    }

    public static final int MEMBERSHIPINFO_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo> membershipInfo_;
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    @java.lang.Override
    public java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo> getMembershipInfoList() {
      return membershipInfo_;
    }
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder> 
        getMembershipInfoOrBuilderList() {
      return membershipInfo_;
    }
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    @java.lang.Override
    public int getMembershipInfoCount() {
      return membershipInfo_.size();
    }
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo getMembershipInfo(int index) {
      return membershipInfo_.get(index);
    }
    /**
     * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder getMembershipInfoOrBuilder(
        int index) {
      return membershipInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCode_ != 0) {
        output.writeUInt32(1, errCode_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(2, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, pid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, version_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(5, overloadWaitTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(6, membershipCount_);
      }
      for (int i = 0; i < membershipInfo_.size(); i++) {
        output.writeMessage(7, membershipInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errCode_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, version_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, overloadWaitTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, membershipCount_);
      }
      for (int i = 0; i < membershipInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, membershipInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse other = (ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse) obj;

      if (getErrCode()
          != other.getErrCode()) return false;
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (hasPid() != other.hasPid()) return false;
      if (hasPid()) {
        if (getPid()
            != other.getPid()) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasOverloadWaitTime() != other.hasOverloadWaitTime()) return false;
      if (hasOverloadWaitTime()) {
        if (getOverloadWaitTime()
            != other.getOverloadWaitTime()) return false;
      }
      if (hasMembershipCount() != other.hasMembershipCount()) return false;
      if (hasMembershipCount()) {
        if (getMembershipCount()
            != other.getMembershipCount()) return false;
      }
      if (!getMembershipInfoList()
          .equals(other.getMembershipInfoList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasPid()) {
        hash = (37 * hash) + PID_FIELD_NUMBER;
        hash = (53 * hash) + getPid();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasOverloadWaitTime()) {
        hash = (37 * hash) + OVERLOADWAITTIME_FIELD_NUMBER;
        hash = (53 * hash) + getOverloadWaitTime();
      }
      if (hasMembershipCount()) {
        hash = (37 * hash) + MEMBERSHIPCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getMembershipCount();
      }
      if (getMembershipInfoCount() > 0) {
        hash = (37 * hash) + MEMBERSHIPINFO_FIELD_NUMBER;
        hash = (53 * hash) + getMembershipInfoList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KVResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KVResponse)
        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.class, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        errCode_ = 0;
        value_ = com.google.protobuf.ByteString.EMPTY;
        pid_ = 0;
        version_ = 0;
        overloadWaitTime_ = 0;
        membershipCount_ = 0;
        if (membershipInfoBuilder_ == null) {
          membershipInfo_ = java.util.Collections.emptyList();
        } else {
          membershipInfo_ = null;
          membershipInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse build() {
        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse buildPartial() {
        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result = new ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result) {
        if (membershipInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0)) {
            membershipInfo_ = java.util.Collections.unmodifiableList(membershipInfo_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.membershipInfo_ = membershipInfo_;
        } else {
          result.membershipInfo_ = membershipInfoBuilder_.build();
        }
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.errCode_ = errCode_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pid_ = pid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.overloadWaitTime_ = overloadWaitTime_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.membershipCount_ = membershipCount_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse other) {
        if (other == ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.getDefaultInstance()) return this;
        if (other.getErrCode() != 0) {
          setErrCode(other.getErrCode());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasOverloadWaitTime()) {
          setOverloadWaitTime(other.getOverloadWaitTime());
        }
        if (other.hasMembershipCount()) {
          setMembershipCount(other.getMembershipCount());
        }
        if (membershipInfoBuilder_ == null) {
          if (!other.membershipInfo_.isEmpty()) {
            if (membershipInfo_.isEmpty()) {
              membershipInfo_ = other.membershipInfo_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureMembershipInfoIsMutable();
              membershipInfo_.addAll(other.membershipInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.membershipInfo_.isEmpty()) {
            if (membershipInfoBuilder_.isEmpty()) {
              membershipInfoBuilder_.dispose();
              membershipInfoBuilder_ = null;
              membershipInfo_ = other.membershipInfo_;
              bitField0_ = (bitField0_ & ~0x00000040);
              membershipInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMembershipInfoFieldBuilder() : null;
            } else {
              membershipInfoBuilder_.addAllMessages(other.membershipInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                errCode_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                pid_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                overloadWaitTime_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                membershipCount_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo m =
                    input.readMessage(
                        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.parser(),
                        extensionRegistry);
                if (membershipInfoBuilder_ == null) {
                  ensureMembershipInfoIsMutable();
                  membershipInfo_.add(m);
                } else {
                  membershipInfoBuilder_.addMessage(m);
                }
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int errCode_ ;
      /**
       * <code>uint32 errCode = 1;</code>
       * @return The errCode.
       */
      @java.lang.Override
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>uint32 errCode = 1;</code>
       * @param value The errCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrCode(int value) {
        
        errCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 errCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 2;</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>optional int32 pid = 3;</code>
       * @return Whether the pid field is set.
       */
      @java.lang.Override
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 pid = 3;</code>
       * @return The pid.
       */
      @java.lang.Override
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 3;</code>
       * @param value The pid to set.
       * @return This builder for chaining.
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>optional int32 version = 4;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0;
        onChanged();
        return this;
      }

      private int overloadWaitTime_ ;
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @return Whether the overloadWaitTime field is set.
       */
      @java.lang.Override
      public boolean hasOverloadWaitTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @return The overloadWaitTime.
       */
      @java.lang.Override
      public int getOverloadWaitTime() {
        return overloadWaitTime_;
      }
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @param value The overloadWaitTime to set.
       * @return This builder for chaining.
       */
      public Builder setOverloadWaitTime(int value) {
        
        overloadWaitTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOverloadWaitTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        overloadWaitTime_ = 0;
        onChanged();
        return this;
      }

      private int membershipCount_ ;
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @return Whether the membershipCount field is set.
       */
      @java.lang.Override
      public boolean hasMembershipCount() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @return The membershipCount.
       */
      @java.lang.Override
      public int getMembershipCount() {
        return membershipCount_;
      }
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @param value The membershipCount to set.
       * @return This builder for chaining.
       */
      public Builder setMembershipCount(int value) {
        
        membershipCount_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMembershipCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        membershipCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo> membershipInfo_ =
        java.util.Collections.emptyList();
      private void ensureMembershipInfoIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          membershipInfo_ = new java.util.ArrayList<ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo>(membershipInfo_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder> membershipInfoBuilder_;

      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo> getMembershipInfoList() {
        if (membershipInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(membershipInfo_);
        } else {
          return membershipInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public int getMembershipInfoCount() {
        if (membershipInfoBuilder_ == null) {
          return membershipInfo_.size();
        } else {
          return membershipInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo getMembershipInfo(int index) {
        if (membershipInfoBuilder_ == null) {
          return membershipInfo_.get(index);
        } else {
          return membershipInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder setMembershipInfo(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo value) {
        if (membershipInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembershipInfoIsMutable();
          membershipInfo_.set(index, value);
          onChanged();
        } else {
          membershipInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder setMembershipInfo(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder builderForValue) {
        if (membershipInfoBuilder_ == null) {
          ensureMembershipInfoIsMutable();
          membershipInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          membershipInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder addMembershipInfo(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo value) {
        if (membershipInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembershipInfoIsMutable();
          membershipInfo_.add(value);
          onChanged();
        } else {
          membershipInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder addMembershipInfo(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo value) {
        if (membershipInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembershipInfoIsMutable();
          membershipInfo_.add(index, value);
          onChanged();
        } else {
          membershipInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder addMembershipInfo(
          ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder builderForValue) {
        if (membershipInfoBuilder_ == null) {
          ensureMembershipInfoIsMutable();
          membershipInfo_.add(builderForValue.build());
          onChanged();
        } else {
          membershipInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder addMembershipInfo(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder builderForValue) {
        if (membershipInfoBuilder_ == null) {
          ensureMembershipInfoIsMutable();
          membershipInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          membershipInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder addAllMembershipInfo(
          java.lang.Iterable<? extends ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo> values) {
        if (membershipInfoBuilder_ == null) {
          ensureMembershipInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, membershipInfo_);
          onChanged();
        } else {
          membershipInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder clearMembershipInfo() {
        if (membershipInfoBuilder_ == null) {
          membershipInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          membershipInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public Builder removeMembershipInfo(int index) {
        if (membershipInfoBuilder_ == null) {
          ensureMembershipInfoIsMutable();
          membershipInfo_.remove(index);
          onChanged();
        } else {
          membershipInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder getMembershipInfoBuilder(
          int index) {
        return getMembershipInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder getMembershipInfoOrBuilder(
          int index) {
        if (membershipInfoBuilder_ == null) {
          return membershipInfo_.get(index);  } else {
          return membershipInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public java.util.List<? extends ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder> 
           getMembershipInfoOrBuilderList() {
        if (membershipInfoBuilder_ != null) {
          return membershipInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(membershipInfo_);
        }
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder addMembershipInfoBuilder() {
        return getMembershipInfoFieldBuilder().addBuilder(
            ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder addMembershipInfoBuilder(
          int index) {
        return getMembershipInfoFieldBuilder().addBuilder(
            index, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .KVResponse.MembershipInfo membershipInfo = 7;</code>
       */
      public java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder> 
           getMembershipInfoBuilderList() {
        return getMembershipInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder> 
          getMembershipInfoFieldBuilder() {
        if (membershipInfoBuilder_ == null) {
          membershipInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfo.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.MembershipInfoOrBuilder>(
                  membershipInfo_,
                  ((bitField0_ & 0x00000040) != 0),
                  getParentForChildren(),
                  isClean());
          membershipInfo_ = null;
        }
        return membershipInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KVResponse)
    }

    // @@protoc_insertion_point(class_scope:KVResponse)
    private static final ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse();
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KVResponse>
        PARSER = new com.google.protobuf.AbstractParser<KVResponse>() {
      @java.lang.Override
      public KVResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KVResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KVResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KVResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KVResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KVResponse_MembershipInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KVResponse_MembershipInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026KeyValueResponse.proto\"\306\002\n\nKVResponse\022" +
      "\017\n\007errCode\030\001 \001(\r\022\022\n\005value\030\002 \001(\014H\000\210\001\001\022\020\n\003" +
      "pid\030\003 \001(\005H\001\210\001\001\022\024\n\007version\030\004 \001(\005H\002\210\001\001\022\035\n\020" +
      "overloadWaitTime\030\005 \001(\005H\003\210\001\001\022\034\n\017membershi" +
      "pCount\030\006 \001(\005H\004\210\001\001\0222\n\016membershipInfo\030\007 \003(" +
      "\0132\032.KVResponse.MembershipInfo\0323\n\016Members" +
      "hipInfo\022\023\n\013addressPair\030\001 \001(\t\022\014\n\004time\030\002 \001" +
      "(\003B\010\n\006_valueB\006\n\004_pidB\n\n\010_versionB\023\n\021_ove" +
      "rloadWaitTimeB\022\n\020_membershipCountB0\n\034ca." +
      "NetSysLab.ProtocolBuffersB\020KeyValueRespo" +
      "nseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_KVResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KVResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KVResponse_descriptor,
        new java.lang.String[] { "ErrCode", "Value", "Pid", "Version", "OverloadWaitTime", "MembershipCount", "MembershipInfo", "Value", "Pid", "Version", "OverloadWaitTime", "MembershipCount", });
    internal_static_KVResponse_MembershipInfo_descriptor =
      internal_static_KVResponse_descriptor.getNestedTypes().get(0);
    internal_static_KVResponse_MembershipInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KVResponse_MembershipInfo_descriptor,
        new java.lang.String[] { "AddressPair", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
